[project]
name = "bbcode"
version = "1.2.0"
description = "A pure python bbcode parser and formatter."
authors = [{ name = "Dan Watson", email = "dcwatson@gmail.com" }]
readme = "README.md"
requires-python = ">=3.10"
license = { text = "BSD" }
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Topic :: Text Processing :: Markup",
]

[project.urls]
Homepage = "https://github.com/dcwatson/bbcode"
Documentation = "https://dcwatson.github.io/bbcode/"

[project.scripts]
bbcode = "bbcode:main"

[build-system]
requires = ["uv_build>=0.12,<0.13"]
build-backend = "uv_build"

[dependency-groups]
dev = ["mkdocs-material>=9.5.42", "mkdocs>=1.6.1"]

[tool.ruff.lint]
extend-select = ["I"]
ignore = [
    "B005",   # strip-with-multi-characters
    "RUF059", # unused-unpacked-variable
    "UP031",  # printf-string-formatting
]
